# .github/workflows/ci.yml

name: CI Pipeline Vue 3

# Déclencheurs du workflow
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Ou la version LTS que vous préférez/utilisez
          cache: 'npm' # Active la mise en cache pour npm

      - name: Install dependencies
        run: npm ci

      - name: Check Formatting
        run: npx prettier --check src/

      - name: Run Linters
        run: npm run lint

      - name: Type Check
        run: npm run type-check


      - name: Run Unit Tests
        run: npm run test:unit

      - name: Build Application
        run: npm run build
