# .github/workflows/ci.yml

name: CI Pipeline Vue 3

# Déclencheurs du workflow
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Check Formatting
        run: npx prettier --check src/

      - name: Run Linters
        run: pnpm run lint:oxlint

      - name: Type Check
        run: pnpm run type-check

      - name: Run Unit Tests
        run: pnpm run test:unit

      - name: Build Application
        run: pnpm run build

